import { db } from '@/db';
import { resources } from '@/db/schema';

async function main() {
    const sampleResources = [
        {
            title: 'SWAYAM Python Programming',
            url: 'https://swayam.gov.in/nd1_noc20_cs30/preview',
            type: 'course',
            tags: 'python,programming,beginner,free',
            locale: 'en',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'edX Introduction to SQL',
            url: 'https://www.edx.org/course/introduction-to-sql',
            type: 'course',
            tags: 'sql,database,beginner',
            locale: 'en',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'YouTube Free Data Science Playlist',
            url: 'https://www.youtube.com/playlist?list=PLQVvvaa0QuDfKTOs_8yNfqtKdreRkKeK9',
            type: 'video',
            tags: 'datascience,python,free,intermediate',
            locale: 'en',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'MIT OpenCourseWare Computer Science',
            url: 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/',
            type: 'course',
            tags: 'cs,free,advanced',
            locale: 'en',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Coursera Machine Learning Course',
            url: 'https://www.coursera.org/learn/machine-learning',
            type: 'course',
            tags: 'ml,python,beginner',
            locale: 'en',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'JavaScript: The Complete Guide 2024',
            url: 'https://www.udemy.com/course/javascript-the-complete-guide-2020-beginner-advanced/',
            type: 'course',
            tags: 'javascript,web,frontend,intermediate',
            locale: 'en',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Effective Java 3rd Edition',
            url: 'https://www.amazon.com/Effective-Java-Joshua-Bloch/dp/0134685997',
            type: 'book',
            tags: 'java,programming,advanced',
            locale: 'en',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'React Documentation Tutorial',
            url: 'https://react.dev/learn',
            type: 'article',
            tags: 'react,javascript,frontend,free,beginner',
            locale: 'en',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Node.js Master Class',
            url: 'https://www.udemy.com/course/nodejs-master-class/',
            type: 'course',
            tags: 'nodejs,javascript,backend,intermediate',
            locale: 'en',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            title: 'The Art of Communication',
            url: 'https://www.coursera.org/learn/communication-skills',
            type: 'course',
            tags: 'communication,soft-skills,beginner',
            locale: 'en',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            title: 'Leadership Principles and Practice',
            url: 'https://www.edx.org/course/leadership-principles-and-practice',
            type: 'course',
            tags: 'leadership,management,intermediate',
            locale: 'en',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            title: 'Project Management Professional (PMP) Prep',
            url: 'https://www.udemy.com/course/pmp-project-management-professional/',
            type: 'course',
            tags: 'project-management,leadership,advanced',
            locale: 'en',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            title: 'Web Development Bootcamp 2024',
            url: 'https://www.udemy.com/course/the-web-developer-bootcamp/',
            type: 'course',
            tags: 'web-development,javascript,html,css,beginner',
            locale: 'en',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            title: 'Mobile App Development with Flutter',
            url: 'https://www.coursera.org/learn/flutter-mobile-development',
            type: 'course',
            tags: 'mobile,flutter,dart,intermediate',
            locale: 'en',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            title: 'AWS Cloud Practitioner Essentials',
            url: 'https://www.aws.training/Details/eCloudPractitionerEssentials',
            type: 'course',
            tags: 'cloud,aws,beginner',
            locale: 'en',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            title: 'Clean Code: Writing Code for Humans',
            url: 'https://www.pluralsight.com/courses/code-clean-writing-code-humans',
            type: 'video',
            tags: 'programming,coding-standards,intermediate',
            locale: 'en',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            title: 'Design Patterns in Modern C++',
            url: 'https://www.udemy.com/course/design-patterns-modern-cpp/',
            type: 'course',
            tags: 'cpp,design-patterns,advanced',
            locale: 'en',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            title: 'The Pragmatic Programmer Book',
            url: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
            type: 'book',
            tags: 'programming,career,advanced',
            locale: 'en',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            title: 'DevOps Tutorial - Docker and Kubernetes',
            url: 'https://www.youtube.com/watch?v=X48VuDVv0oM',
            type: 'video',
            tags: 'devops,docker,kubernetes,free,intermediate',
            locale: 'en',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
    ];

    await db.insert(resources).values(sampleResources);
    
    console.log('✅ Resources seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});